# fly.toml app configuration file generated for blog-list-by-bt on 2023-07-07T15:55:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blog-list-by-bt"
primary_region = "arn"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
