POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRzbWl0aCIsImlkIjoiNjRjY2FiOGMzZGQzMzZmMTdiMTE3MmQ2IiwiaWF0IjoxNjkxMTM1NzQ1LCJleHAiOjE2OTExMzU4MDV9.r5tI5xGoSZLkJItRdAuPpedavd8akJ4jQwNpb4d8bVs

{
  "title": "JWT are good for user authentication",
  "author": "John Expert",
  "url": "https://userauthentication101.com"
}


###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Brian Smith",
  "url": "https://medium.com/how-to-get-an-error"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "How to Get an Error",
  "url": "https://medium.com/how-to-get-an-error"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "How to Get an Error",
  "author": "Brian Smith"
}