POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRzbWl0aCIsImlkIjoiNjRjY2FiOGMzZGQzMzZmMTdiMTE3MmQ2IiwiaWF0IjoxNjkxMTM2NDc3LCJleHAiOjE2OTExNDAwNzd9.wtvEPp35RUpbcfozAyVtjZ0XDj63C9RE4Yh1J5Acy74

{
  "title": "How to move token extraction to middleware",
  "author": "Eric Refactor",
  "url": "https://middlewaremagic.com"
}


###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Brian Smith",
  "url": "https://medium.com/how-to-get-an-error"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "How to Get an Error",
  "url": "https://medium.com/how-to-get-an-error"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "How to Get an Error",
  "author": "Brian Smith"
}