POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Adding new blog with that is linked to user",
  "author": "Test Tester",
  "url": "https://test.blog.com",
  "userId": "64cb9de1a5217d8ac4f1a22d"
}


###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "author": "Brian Smith",
  "url": "https://medium.com/how-to-get-an-error"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "How to Get an Error",
  "url": "https://medium.com/how-to-get-an-error"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "How to Get an Error",
  "author": "Brian Smith"
}